### ISSUE TITLE
trivy k8s - on OpenShift

### ISSUE THREAD

**Issue by mtcolman** [aquasecurity/trivy-kubernetes#30]
Hi, I've just tried using `trivy k8s`  with an OpenShift cluster:
```
trivy k8s -n test--severity=CRITICAL --report=all
```

and get:
```
FATAL   get k8s artifacts error: failed listing resources for gvr: config.openshift.io/v1, Resource=ingresses - the server could not find the requested resource
```

When I list resources, I can see:
```
oc api-resources --verbs=list | sed '1p;/ingresses/!d'
NAME                              SHORTNAMES          APIVERSION                                    NAMESPACED   KIND
ingresses                                             config.openshift.io/v1                        false        Ingress
ingresses                         ing                 networking.k8s.io/v1                          true         Ingress
```

The error message appears to come from: https://github.com/aquasecurity/trivy-kubernetes/blob/main/pkg/trivyk8s/trivyk8s.go#L63

When the command is run with `--debug` flag I get:
```
FATAL   get k8s artifacts error:
    github.com/aquasecurity/trivy/pkg/k8s.Run
        /home/runner/work/trivy/trivy/pkg/k8s/run.go:80
  - failed listing resources for gvr: config.openshift.io/v1, Resource=ingresses - the server could not find the requested resource
```

Is this a bug, expected, unforeseen etc? I'm wondering if it has something to do with the fact the `ingress` resource in question, from the `config.openshift.io/v1` API group is stated to be clusterwide, not namespaced (whereas the `networking.k8s.io` one is)?

From [OpenShift docs](https://docs.openshift.com/container-platform/4.10/networking/ingress-operator.html) I can see it says:
> The installation program generates an asset with an Ingress resource in the config.openshift.io API group.
> This Ingress resource defines the cluster-wide configuration for Ingress.

And therefore I wondered if maybe that caused issues for [this code](https://github.com/aquasecurity/trivy-kubernetes/blob/main/pkg/k8s/k8s.go#L159) where `Ingresss` is in the `getNamespaceResources()` function?

Thanks!

**Comment by josedonizetti** [comment]
@mtcolman Thanks for reporting. This is definitely a bug, and I also think the reason is due to querying the ` config.openshift.io/v1/ingresses` as if it is namespaced. I still didn't have time to get a openshift cluster to run some tests, but another good insight here, is that we should not error and exit the scanning of a cluter/namespace because of only one single resource.

**Comment by mtcolman** [comment]
Hi @josedonizetti I was just wondering if you've been able to test this as I'm really keen to have a play with it on OpenShift (even if you could just add the error handling so that it continues onto the next resource)?

**Comment by josedonizetti** [comment]
@mtcolman Yes, I agree we shouldn’t exit the whole scan due to one resource not found. I'm going to close this issue here, and move it to the trivy project, we are tracking everything there now and it simplifies for me to prioritize the work on it. 

I broke it in two issues:
- https://github.com/aquasecurity/trivy/issues/2257
- https://github.com/aquasecurity/trivy/issues/2258

Thank you
